name: Run RuboCop

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Setup gems
      run: |
        cp test/support/Gemfile.local Gemfile
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: |
        bundle exec rubocop -S
